// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,      // No guardar sesión entre cierres del browser
    autoRefreshToken: false,    // No renovar el token automáticamente
    storage: sessionStorage,    // Usar sessionStorage en lugar de localStorage (se borra al cerrar el tab)
  }
});

// Setea la org activa en la sesión de Postgres para que RLS use get_active_org()
// Debe llamarse cada vez que el usuario selecciona o cambia de organización
export const setActiveOrg = async (orgId: string) => {
  await supabase.rpc('set_active_org', { org_id: orgId });
};
